Holara/Areas/User/Controllers/CoverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Holara.Data;
using Holara.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Holara.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class CoverController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CoverController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //Get Current User Id
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //Get the Friend List of current User
            var friendlist = _db.Friends
                .Include(u => u.ApplicationUser1)
                .Include(u => u.ApplicationUser2)
                .Where(x => (x.User1Id == claim.Value || x.User2Id == claim.Value))
                .Where(x => x.IsConfirmed)
                .ToList();

            //Create new List of Posts
            var posts = new List<Post>();

            //Get List of Post of Every Friend of Current User
            foreach (var item in friendlist)
            {   
                if(item.User1Id == claim.Value)
                {
                    var postList = _db.Posts.Include(u => u.User).Where(x => x.UserId == item.User2Id).Where(x => x.IsPublicOrNot).ToList();
                    posts.AddRange(postList);
                }
                else if(item.User2Id == claim.Value)
                {
                    var postList = _db.Posts.Include(u => u.User).Where(x => x.UserId == item.User1Id).Where(x => x.IsPublicOrNot).ToList();
                    posts.AddRange(postList);
                }
            }

            //Get the post of Current User
            var currentuserPosts = _db.Posts.Include(u => u.User).Where(u => u.UserId == claim.Value).ToList();

            //Add Current User Post List to new List
            posts.AddRange(currentuserPosts);

            //Order by Date and time of Post 
            var postsList = posts.OrderByDescending(x => x.PostDateAndTime).ToList();
            return View(postsList);
        }
    }
}

Holara/Areas/User/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Holara.Data;
using Holara.Models;
using Holara.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Holara.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class FriendsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public FriendsController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var applicationUsers = _db.ApplicationUsers.Where(m => m.Id != claim.Value).ToList();

            return View(applicationUsers);
        }

        public async Task<IActionResult> ConfirmRequest(string id)
        {
            var friend = await _db.ApplicationUsers.FindAsync(id);
            var friends = new FriendsViewModel
            {
                applicationUser = await _db.ApplicationUsers.FindAsync(id),
                friends =  _db.Friends.ToList()
        };
            return View(friends);
        }

        [HttpPost, ActionName("ConfirmRequest")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmRequestPost(string id)
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string requestSender = claim.Value;
            string requestAceptor = id;
            var presentDate = DateTime.Now;

            TempData["Messege"] = "Successfully send request to ";
            var friends = new Friends();
            friends.User1Id = requestSender;
            friends.User2Id = requestAceptor;
            friends.RequestDate = presentDate;
            friends.IsConfirmed = false;

            _db.Friends.Add(friends);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(UserDetail), new { @id=id });
        }

        public async Task<IActionResult> UserDetail(string id)
        {
            ViewBag.messege = TempData["Messege"];
            var user = await _db.ApplicationUsers.FindAsync(id);
            return View(user);
        }

        public async Task<IActionResult> CancelRequest(int id)
        {
            var request = await _db.Friends.FindAsync(id);
            _db.Friends.Remove(request);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Holara/Areas/User/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Holara.Data;
using Holara.Models;
using Holara.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Holara.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;


        public PostController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ViewBag.messege = TempData["Messege"];
            var postList = await _db.Posts.Include(u => u.User).Where(u => u.UserId == claim.Value).OrderByDescending(m => m.PostDateAndTime).ToListAsync();
            return View(postList);
        }

        //GET: Create 
        public IActionResult Create()
        {
            return View();
        }

        //Post: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post)
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (!ModelState.IsValid)
            {
                return View(post);
            }

            _db.Posts.Add(post);
            await _db.SaveChangesAsync();

            //Saving Image
            var webRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            var postInDB = await _db.Posts.FindAsync(post.Id);

            if (files.Count != 0)
            {
                var upload = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(upload, post.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                postInDB.Image = @"\" + SD.ImageFolder + @"\" + post.Id + extension;
            }
            postInDB.UserId = claim.Value;
            postInDB.PostDateAndTime = DateTime.Now;
            TempData["Messege"] = "Post Added Successfully";
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Get: Edit
        public async Task<IActionResult> Edit(int id)
        {
            var postInDB = await _db.Posts.FindAsync(id);
            return View(postInDB);
        }

        //Post : Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Post post)
        {
            if(ModelState.IsValid)
            {
                var webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var postInDB = await _db.Posts.FindAsync(id);
                if(files.Count != 0 && files[0] != null)
                {
                    var upload = Path.Combine(webRootPath, SD.ImageFolder);
                    var old_extension = Path.GetExtension(postInDB.Image);
                    var new_extension = Path.GetExtension(files[0].FileName);
                    if(System.IO.File.Exists(Path.Combine(upload, postInDB.Id + old_extension)))
                    {
                        System.IO.File.Delete(Path.Combine(upload, postInDB.Id + old_extension));
                    }
                    using (var fileStream = new FileStream(Path.Combine(upload, postInDB.Id + new_extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    post.Image = @"\" + SD.ImageFolder + @"\" + postInDB.Id + new_extension;
                }
                if(post.Image != null)
                {
                    postInDB.Image = post.Image;
                }
                postInDB.PostDescription = post.PostDescription;
                postInDB.IsPublicOrNot = post.IsPublicOrNot;
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        //Get: Delete
        public IActionResult Delete(int? id)
        {
            var postInDB = _db.Posts.Find(id);
            return View(postInDB);
        }

        //Post: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var postInDb = await _db.Posts.FindAsync(id);
            if(postInDb == null)
            {
                return NotFound();
            }
            _db.Posts.Remove(postInDb);
            await _db.SaveChangesAsync();
            ViewBag.Messege = "Post Deleted Successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

Holara/Areas/User/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Holara.Data;
using Holara.Models;
using Holara.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;

namespace Holara.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        public ProfileController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
        }


        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ViewBag.messege = TempData["Messege"];
            var userProfile =await _db.ApplicationUsers.FindAsync(claim.Value);
            return View(userProfile);
        }

        //Get: Edit
        public async Task<IActionResult> Edit()
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var user = await _db.ApplicationUsers.FindAsync(claim.Value);
            return View(user);
        }

        //Post: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser applicationUser)
        {
            ClaimsPrincipal currentUser = User;
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                var user = await _db.ApplicationUsers.FindAsync(claim.Value);
                user.Name = applicationUser.Name;
                user.UserName = applicationUser.UserName;
                user.Email = applicationUser.Email;
                user.PhoneNumber = applicationUser.PhoneNumber;

                //Saving Image
                var webrootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                
                if(files.Count > 0 && files[0] != null)
                {
                    var upload = Path.Combine(webrootPath, SD.UserImageFolder);
                    var new_extension = Path.GetExtension(files[0].FileName);
                    var old_extension = Path.GetExtension(user.Image);

                    if(System.IO.File.Exists(Path.Combine(upload, user.Id + old_extension)))
                    {
                        System.IO.File.Delete(Path.Combine(upload, user.Id + old_extension));
                    }

                    using (var fileStream = new FileStream(Path.Combine(upload, user.Id + new_extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    applicationUser.Image = @"\" + SD.UserImageFolder + @"\" + user.Id + new_extension;
                }
                if(applicationUser.Image != null)
                {
                    user.Image = applicationUser.Image;
                }
                TempData["Messege"] = "Profile Updated Successfully";
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }
    }
}

Holara/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<IdentityUser> _userManager
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Holara</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="~/lib/Skeleton/images/logo.png">

    <environment include="Development">
        <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/style.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/normalize.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/skeleton.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/animate.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/style.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/normalize.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/skeleton.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/animate.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <!--Navigation-->
    <nav class="navigation sticky">
        <ul>
            <li class="nav-brand animated heartBeat logo"><a asp-area="User" asp-controller="Home" asp-action="Index">Holara</a></li>

            @if (!SignInManager.IsSignedIn(User))
            {
                
                <partial name="_LoginPartial" />
            }
            else
            {
                <li><a asp-area="User" asp-controller="Post" asp-action="Index">Timeline</a></li>
            }
        </ul>
    </nav>
    <!--Section 1-->
    <section class="section1">
        <div>
            <div class="row">
                <div class="nine columns col1 animated slideInUp">
                    @RenderBody()
                </div>
                <div class="three columns col3 ads1">
                    <div class="container asd2">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a class="button button-primary" style="margin-top: 30px;" asp-area="User" asp-controller="Post" asp-action="Create">Add New Post</a>
                        }

                        <div style="margin-top:25px !important;" class="panel-header1 animated bounceInRight ads3">
                            <img src="https://image.shutterstock.com/image-vector/potato-chips-advertisement-spicy-flavor-260nw-642316276.jpg" class="ad-image" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <environment include="Development">
        <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
        <script src="~/lib/Skeleton/js/script.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
        <script src="~/lib/Skeleton/js/script.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

Holara/Views/Shared/_UserLayout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<IdentityUser> _userManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Holara</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="~/lib/Skeleton/images/logo.png">
    <style>
        .dropdown {
            float: left;
            overflow: hidden;
            margin-left: -30px;
        }

            .dropdown .dropbtn {
                font-size: 12px;
                border: none;
                outline: none;
                color: black;
                background-color: inherit;
                margin-top: -10px;
            }
            .dropbtn a {
                text-decoration:none;
                color:black;
            }

            

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: #ddd;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .badge {
            position:relative;
        }

        .badge[data-badge]:after {
            content:attr(data-badge);
            position:absolute;
            margin-left:7px;
            color:black;

        }
        .zoom:hover {
            transform:scale(2.5);
            transition: transform 0.4s;
        }
        #notification {
            text-align:center;
        }
        .notify {
            color: red;
            font-size:16px;
            letter-spacing:1px;
            text-transform:uppercase;
        }
    </style>

    <environment include="Development">
        <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/normalize.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/skeleton.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/style.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/animate.css">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/normalize.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/skeleton.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/style.css">
        <link rel="stylesheet" href="~/lib/Skeleton/css/animate.css">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>
</head>
<body>
    <!--Navigation-->
    <nav class="navigationfor sticky">
        <ul>
            <li class="nav-brand animated heartBeat logo"><a asp-area="User" asp-controller="Cover" asp-action="Index">Holara</a></li>
            <li class="animated bounceInDown"><a asp-area="User" asp-controller="Post" asp-action="Index">Timeline</a></li>
            <li class="animated bounceInUp"><a asp-area="User" asp-controller="Profile" asp-action="Index">Profile</a></li>
            <li class="animated bounceInDown" style="margin-left:60px;">
                <div class="dropdown">
                    <a class="dropbtn" style="font-size:15px; ">Friends</a>
                    <div class="dropdown-content">
                        <a asp-area="User" asp-controller="Friends" asp-action="Index">Find Friends</a>
                        <a asp-area="User" asp-controller="FriendsList" asp-action="Index">Friends List</a>
                        <a asp-area="User" asp-controller="FriendRequest" asp-action="Index">Friend Requests</a>
                    </div>
                </div>
            </li>
            <partial name="_LoginPartial" />
        </ul>
    </nav>
    <!--Section 1-->
    <section class="section1">
        <div>
            <div class="row">
                <div class="nine columns col1 animated slideInUp">
                    @RenderBody()
                </div>
                <div class="three columns col3 ads1">
                    <div class="container asd2">
                        <a class="button button-primary" style="margin-top: 30px;" asp-area="User" asp-controller="Post" asp-action="Create">Add New Post</a>
                        <div style="margin-top:8px !important;" class="panel-header1 animated bounceInRight ads3">
                            <img src="https://image.shutterstock.com/image-vector/potato-chips-advertisement-spicy-flavor-260nw-642316276.jpg" class="ad-image" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <environment include="Development">
        <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
        <script src="~/lib/Skeleton/js/script.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
        <script src="~/lib/Skeleton/js/script.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>